<div class="console">
    <form action="<?php echo $request->getPath(); ?>" method="post">
        <div class="resource">
            <input type="text" name="url" value="help/configuration.json">
            <select name="method">
                <option value="GET">GET</option>
                <option value="POST">POST</option>
            </select>
            <input type="submit" name="submit" value="Request!">
        </div>
        <div class="options"></div>
    </form>
    <?php if (isset($result)) { ?>
        <div class="result"><div class="raw"><?php echo $result['data']; ?></div></div>
    <?php } ?>
</div>