<?php foreach ($services as $name => $service) { ?>
    <?php if ($service === null) continue; ?>
    <?php if ($services->isAuthenticated($name)) { ?>
        <a href="/<?php echo $version . '/' . $name; ?>" class="service">
    <?php } else { ?>
        <a href="/<?php echo $version . '/' . $name; ?>/authorize" class="service">
    <?php } ?>
        <article class="<?php echo strtolower($name); ?>" title="<?php echo $name; ?>" class="<?php echo strtolower($name); ?>">
            <?php if (in_array(strtolower($name), ['twitter', 'etsy', 'fitbit'], true)) { // placeholder til font awesome fixes its font ?>
                <i class="fa fa-circle-o"></i>
            <?php } else { ?>
                <i class="fa fa-<?php echo strtolower($name); ?>"></i>
            <?php } ?>
            <?php if ($services->isAuthenticated($name)) { ?>
                <p>Authenticated</p>
            <?php } else { ?>
                <p>Request token</p>
            <?php } ?>
        </article>
    </a>
<?php } ?>