<?php
$icons = [
    'twitter'       => '&#xf099;',
    'bitbucket'     => '&#xf171;',
    'etsy'          => '&#xf10c;', // default
    'fitbit'        => '&#xf10c;', // default
    'flickr'        => '&#xf16e;',
    'tumblr'        => '&#xf173;',
    'xing'          => '&#xf168;',
    'amazon'        => '&#xf10c;', // default
    'bitly'         => '&#xf10c;', // default
    'box'           => '&#xf10c;', // default
    'dailymotion'   => '&#xf10c;', // default
    'dropbox'       => '&#xf16b;',
    'facebook'      => '&#xf09a;',
    'foursquare'    => '&#xf180;',
    'github'        => '&#xf09b;',
    'google'        => '&#xf0d5;',
];
?>
<?php foreach ($services as $name => $service) { ?>
    <?php if ($service === null) continue; ?>
    <?php if ($services->isAuthenticated($name)) { ?>
        <a href="/<?php echo $version . '/' . $name; ?>" class="service">
    <?php } else { ?>
        <a href="/<?php echo $version . '/' . $name; ?>/authorize" class="service">
    <?php } ?>
        <article class="<?php echo strtolower($name); ?>" title="<?php echo $name; ?>" class="<?php echo strtolower($name); ?>">
            <i class="fa"><?php echo $icons[strtolower($name)]; ?></i>
            <?php if ($services->isAuthenticated($name)) { ?>
                <p>Authenticated</p>
            <?php } else { ?>
                <p>Request token</p>
            <?php } ?>
        </article>
    </a>
<?php } ?>